### ISSUE TITLE
the args.opt_stepNs is invalid

### ISSUE THREAD

**Issue by chensjtu** [cvlab-stonybrook/s-volsdf#2]
I met "no matches found: opt_stepNs=[100000,0,0]" maybe the args.opt_stepNs cannot passed into the model

**Comment by hao-yu-wu** [comment]
Hi, although I didn't face this problem, it seems it's related to shell interpretation.
Can you try something like this?
`python runner.py gpu=0 testlist=scan106 outdir=exps_mvs exps_folder=exps_vsdf "opt_stepNs=[10000,0,0]"`
