### ISSUE TITLE
How to export a mesh model

### ISSUE THREAD

**Issue by asabxkh74126154** [cvlab-stonybrook/s-volsdf#5]
Hello! Thank you very much for sharing such great code. I would like to ask how to export the mesh model shown in the paper. I only exported the point cloud model when I ran the code. I hope I can get your advice.

**Comment by hao-yu-wu** [comment]
Hi, please check `--eval_mesh` option in `eval_vsdf.py`, for example:
`python eval_vsdf.py --conf dtu  --data_dir_root data_s_volsdf --scan_ids 106 --eval_rendering --gpu 0 --expname ours --exps_folder exps_vsdf --evals_folder exps_result --eval_mesh`

**Comment by asabxkh74126154** [comment]
Thank you very much for your reply. I also want to ask you a question. How to reconstruct texture after generating mesh? Is this possible using the open source code you provided? hope to get your reply

**Comment by hao-yu-wu** [comment]
It's a bit beyond this repo's capability, but a simple method could be:
after obtaining the colored point cloud and mesh, assign the color of the closest point to the vertex mesh.
Hopefully this helps.

**Comment by asabxkh74126154** [comment]
OK, thank you very much for your answer, it helps me a lot
